version: "3.1"
services:
  db:
    image: docker.io/postgres:latest
    environment:
      POSTGRES_PASSWORD: tododb
      POSTGRES_USER: tododb
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - "./modules/models/target/generated-resources/sql/ddl/auto:/docker-entrypoint-initdb.d"